### PR TITLE
Filter fix

### LINKED ISSUE #164: Filter bar not working as intended
**Is your feature request related to a problem? Please describe.**
Filter is only activated once a user clicks on a sort method, it has inconsistent behavior with filtering.

### PR DESCRIPTION
**Pull request by connielion**
## Changes
1. Defined `updateFilterType` in PokeList and pass it down to FilterBar.
2. Removed Spinner in InfiniteScroll.

## Purpose
Fix filter and sort issue.

## Approach
Invoke setUserDidSort and setFilterType again.

## Testing Steps
User should be able to filter without pressing any sort buttons.

Closes #164

### CODE REVIEW

**Review by Lap343 — APPROVED** [review]
woooo looking good!

**Review by Wolftownn — APPROVED** [review]
Nice! Excited to use the filters on the app for sure.

**Review by Gjhnsn — APPROVED** [review]
🙌

**Comment by dannysanchez559** [comment]
The spinner was clean 🥲

**Pull request merged**
