### PR TITLE
fix(header): fix pokemon number search capability

### LINKED ISSUE #160: searchbar dexnumber inconsistent behavior
**Is your feature request related to a problem? Please describe.**
Searchbar does not always work as intended when entering a pokemon number. The behavior works fine when entering a pokemon name. 
The behavior for entering a pokemon number is inconsistent and only appears to be a problem part of the time. More investigation needs to be done. 

image

### PR DESCRIPTION
**Pull request by dannysanchez559**
## Changes
_List Changes Introduced by this PR_
1. Included capability for user to search by pokemon dex numbers 1<

Closes #160

### CODE REVIEW

**Review by Lap343 — APPROVED** [review]
Looks good

**Review by JorgeLVilla — APPROVED** [review]
Noice job

**Review by connielion — APPROVED** [review]
Looks good.

**Review by Gjhnsn — APPROVED** [review]
Good fix so users can search for single and double digit dex #

**Pull request merged**
